apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: new-service-account-binding
subjects:
  - kind: ServiceAccount
    name: new-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin  # Change this to the appropriate role if needed
  apiGroup: rbac.authorization.k8s.io

