apiVersion: v1
kind: Service
metadata:
  name: flask-app-service  # Name of the service
spec:
  selector:
    app: flask-app  # Match label with pod to route traffic correctly
  ports:
    - protocol: TCP
      port: 8080           # Exposed port within the cluster
      targetPort: 5000     # Port your application listens on inside the container
      nodePort: 31000      # External port accessible on all nodes (adjustable within range 30000-32767)
  type: NodePort          # Expose service as a NodePort
